
<!-- widget grid -->
<section id="widget-grid" class="">

<?php $this->menuitemForm->setAttribute('action', $this->action)?>
<?php $this->menuitemForm->prepare();?>
<?php echo $this->form()->openTag($this->menuitemForm)?>

    <!-- START ROW -->

    <div class="row">

        <!-- NEW COL START -->
        <div class="col-sm-12 col-md-12 col-lg-6 ">

            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false">
                <!-- widget options:
                usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                data-widget-colorbutton="false"
                data-widget-editbutton="false"
                data-widget-togglebutton="false"
                data-widget-deletebutton="false"
                data-widget-fullscreenbutton="false"
                data-widget-custombutton="false"
                data-widget-collapsed="true"
                data-widget-sortable="false"

                -->
                <header>
                    <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                    <h2>General</h2>

                </header>

                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body no-padding">
                        <div class="smart-form">
                            <fieldset> 
                                <section>
                                    <label class="label"><?php echo $this->translate('Label')?></label>
                                    <label class="input <?php echo ($this->formElementErrors($this->menuitemForm->get('menuitem_label')))?"state-error":""; ?>">
                                        <?php echo $this->formrow($this->menuitemForm->get('menuitem_label')->setAttribute('class', 'input-sm'))?>
                                    </label>
                                </section>
                                
                                <section>
                                    <label class="label"><?php echo $this->translate('Title')?></label>
                                    <label class="input <?php echo ($this->formElementErrors($this->menuitemForm->get('menuitem_title')))?"state-error":""; ?>">
                                        <?php echo $this->formrow($this->menuitemForm->get('menuitem_title')->setAttribute('class', 'input-sm'))?>
                                    </label>
                                </section>
                                
                                <section>
                                    <label class="label"><?php echo $this->translate('URI')?></label>
                                    <label class="input <?php echo ($this->formElementErrors($this->menuitemForm->get('menuitem_uri')))?"state-error":""; ?>">
                                        <?php echo $this->formrow($this->menuitemForm->get('menuitem_uri')->setAttribute('class', 'input-sm'))?>
                                    </label>
                                </section>
                                
                                <section>
                                    <label class="label"><?php echo $this->translate('Parent')?></label>
                                    <label class="input">
                                        <?php echo $this->formrow($this->menuitemForm->get('menuitem_parent_id')->setAttribute('class', 'input-sm'))?>
                                    </label>
                                </section>
                                
                                <?php if($this->menuitemForm->has('menuitem_type')){?>
                                <section>
                                    <label class="label"><?php echo $this->translate('Mega subitem type')?></label>
                                    <label class="input">
                                        <?php echo $this->formrow($this->menuitemForm->get('menuitem_type')->setAttribute('class', 'input-sm'))?>
                                    </label>
                                </section>
                                <?php }?>
                                
                                <section>
                                    <label class="label"><?php echo $this->translate('Order')?></label>
                                    <label class="input">
                                        <?php echo $this->formrow($this->menuitemForm->get('menuitem_weight')->setAttribute('class', 'input-sm'))?>
                                    </label>
                                </section>
                                
                                <section>
                                    <label class="label"><?php echo $this->translate('Target attribute')?></label>
                                    <label class="input">
                                        <?php echo $this->formrow($this->menuitemForm->get('menuitem_target')->setAttribute('class', 'input-sm'))?>
                                    </label>
                                </section>
                                
                                <section>
                                    <label class="label"><?php echo $this->translate('Visible')?></label>
                                    <label class="checkbox">
                                        <?php echo $this->formrow($this->menuitemForm->get('menuitem_visible'))?><i></i>
                                    </label>
                                </section>
                                
                                <?php echo $this->formrow($this->menuitemForm->get('menuitem_menu_id'))?>
                            </fieldset>
                        </div>
                    </div>
                    <!-- end widget content -->

                </div>
                <!-- end widget div -->

            </div>
            <!-- end widget -->
    
        </div>
        <!-- END COL -->
    
    </div>
    
    <!-- END ROW -->
        
    <!-- START ROW -->

    <div class="row">

        <!-- NEW COL START -->
        <div class="col-sm-12 col-md-12 col-lg-12 ">
            <div class="smart-form">
                <footer>
                    <?php echo $this->formButton()->render($this->menuitemForm->get('submit-menuForm'), 'Save menu'); ?>                                                            
                    
                </footer>
            </div>
    
        </div>
        <!-- END COL -->
    
    </div>
    
    <!-- END ROW -->
    
                        
<?php echo $this->form()->closeTag($this->menuitemForm); ?>
</section>
