<!-- RIBBON -->
<div id="ribbon">

	<span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

	<!-- breadcrumb -->
	<ol class="breadcrumb">
		<li>Admin</li><li>Central DB</li><li>View Destinations</li>
	</ol>
	<!-- end breadcrumb -->

	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->

</div>
<!-- MAIN CONTENT -->
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark">
				<i class="fa fa-edit fa-fw "></i> 
					Central DB 
				<span>> 
					View Destinations
				</span>
			</h1>
		</div>
	</div>
	
	<!-- widget grid -->
	<section id="widget-grid" class="">
		
		<!-- START ROW -->
	
		<div class="row">
	
			<!-- NEW COL START -->
			<div class="col-sm-12 col-md-12 col-lg-12 ">
	
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false">
					<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
	
					data-widget-colorbutton="false"
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true"
					data-widget-sortable="false"
	
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
						<h2><?php echo $this->translate('Destinations')?></h2>
	
					</header>
	
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body">
							<div class="smart-form row">
								<section class="col-md-3">
									<label class="label">Select Country</label>
									<label class="select">
										<select class="input-sm" id="country">
											<?php foreach($this->countries as $country): ?>
												<option value="<?php echo $country['id']; ?>" <?php echo ($country['id']==$this->defaultCountryId)?"selected='selected'":""; ?>>
													<?php echo $country['name']; ?>
												</option>
											<?php endforeach; ?>
										</select> <i></i> </label>
								</section>
								<section class="col-md-1 loading-div ui-autocomplete-loading" style="display:none;">
									<img src="/admin-assets/images/select2-spinner.gif"	style="padding-top:32px; padding-left:10px;"/>								
								</section>
							</div>
							<div class="view-destination">
								<?php echo $this->partial('admin/viewdestination/view-destination', array(
									    'destinations' => $this->destinations,								    
									));?>
							</div>
						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
	
				</div>
				<!-- end widget -->
		
			</div>
			<!-- END COL -->			
			
		</div>
		
		<!-- END ROW -->
	</section>
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		
	</div><!-- /.modal -->
</div>

<script src="/admin-assets/js/treeview/jquery-ui.custom.js" type="text/javascript"></script>
<script src="/admin-assets/js/treeview/jquery.cookie.js" type="text/javascript"></script>

<link href="/admin-assets/js/treeview/skin/ui.dynatree.css" rel="stylesheet" type="text/css" id="skinSheet">
<script src="/admin-assets/js/treeview/jquery.dynatree.js" type="text/javascript"></script>

<!-- Start_Exclude: This block is not part of the sample code -->
<link href="/admin-assets/js/treeview/prettify.css" rel="stylesheet">
<script src="/admin-assets/js/treeview/prettify.js" type="text/javascript"></script>
<script src="/admin-assets/js/treeview/sample.js" type="text/javascript"></script>
<script>
	$(function(){
		$('#country').change(function(){
			$('.loading-div').show();
			$.ajax({
				type: "POST",
				url:"/admin/centraldb/viewdestination/viewDestination",
				data: "countryId=" + $(this).find(" :selected").val(),				
			}).done(function(data) {
				$('.view-destination').html(data);
				$('.loading-div').hide();
			});
		});
	});
</script>