<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Travel\Module' => __DIR__ . '/Module.php',
    'Travel\Controller\AccommodationController' => __DIR__ . '/src/Travel/Controller/AccommodationController.php',
    'Travel\Controller\ToursController' => __DIR__ . '/src/Travel/Controller/ToursController.php',
    'TravelTest\Framework\TestCase' => __DIR__ . '/tests/Travel/Framework/TestCase.php',
    'TravelTest\SampleTest' => __DIR__ . '/tests/Travel/SampleTest.php'
);
