<!-- RIBBON -->
<div id="ribbon">

	<span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

	<!-- breadcrumb -->
	<ol class="breadcrumb">
		<li>Admin</li><li>Settings</li><li>Options</li>
	</ol>
	<!-- end breadcrumb -->

	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->

</div>
<!-- MAIN CONTENT -->
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark">
				<i class="fa fa-edit fa-fw "></i> 
					Settings 
				<span>> 
					Options>New Option
				</span>
			</h1>
		</div>
	</div>
	<?php echo $this->partial('admin/options/option-form', array(
    	'optionForm'		=> $this->optionForm,
    	'optionFormErrors'	=> $this->optionFormErrors,
    	'action'			=> $this->url('zfcadmin/settings/options', array('action' => 'edit', 'id' => $this->optionId)),
    ))?>
		
</div>