<!-- RIBBON -->
<div id="ribbon">

	<span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

	<!-- breadcrumb -->
	<ol class="breadcrumb">
		<li>Admin</li><li>Settings</li><li>Providers</li>
	</ol>
	<!-- end breadcrumb -->

	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->

</div>
<!-- MAIN CONTENT -->
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark">
				<i class="fa fa-edit fa-fw "></i> 
					Settings 
				<span>> 
					Providers
				</span>
			</h1>
		</div>
	</div>
	
	<!-- widget grid -->
	<section id="widget-grid" class="">
	
		<!-- START ROW -->
	
		<div class="row">
	
			<!-- NEW COL START -->
			<div class="col-sm-12 col-md-12 col-lg-6 ">
	
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false">
					<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
	
					data-widget-colorbutton="false"
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true"
					data-widget-sortable="false"
	
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
						<h2><?php echo $this->translate('Provider settings')?></h2>
	
					</header>
	
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body no-padding">
							<?php $this->form->prepare(); ?>
							<?php echo $this->form()->openTag($this->form);?>
							<div class="smart-form">
								<header>
									<?php echo $this->translate('RoamFree')?>
								</header>
								<fieldset>
									<section>
										<label class="label"><?php echo $this->translate('Enable')?></label>
										<label class="checkbox">
											<?php echo $this->formrow($this->form->get('roamfree')->get('enable'))?>
											<i></i> </label>
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Roamfree Area Id')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('roamfree')->get('id')))?"state-error":""; ?>">
											<?php echo $this->formtext($this->form->get('roamfree')->get('id')->setAttribute('class', 'input-sm'))?>
										</label>
										<div class="note">Area id of Roamfree for parent area</div>							
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Website ID')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('roamfree')->get('web_id')))?"state-error":""; ?>">
											<?php echo $this->formtext($this->form->get('roamfree')->get('web_id')->setAttribute('class', 'input-sm'))?>
										</label>																	
									</section>
								</fieldset>
								
								<header>
									<?php echo $this->translate('Hotels Combined')?>
								</header>
								
								<fieldset>
									<section>
										<label class="label"><?php echo $this->translate('Enable')?></label>
										<label class="checkbox">
											<?php echo $this->formrow($this->form->get('hotelscombined')->get('enable'))?>
											<i></i> </label>
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Hotels Combined Area Id')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('hotelscombined')->get('id')))?"state-error":""; ?>">
											<?php echo $this->formtext($this->form->get('hotelscombined')->get('id')->setAttribute('class', 'input-sm'))?>
										</label>
										<div class="note">Area Id of Hotels Combined for parent area</div>							
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('WhiteLabel Url')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('hotelscombined')->get('whitelabelurl')))?"state-error":""; ?>">
											<?php echo $this->formtext($this->form->get('hotelscombined')->get('whitelabelurl')->setAttribute('class', 'input-sm'))?>
										</label>																	
									</section>
									
								</fieldset>
								
								<header>
									<?php echo $this->translate('ATDW')?>
								</header>
								
								<fieldset>
									<section>
										<label class="label"><?php echo $this->translate('Enable')?></label>
										<label class="checkbox">
											<?php echo $this->formrow($this->form->get('atdw')->get('enable'))?>
											<i></i> </label>
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('ATDW Area Id')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('atdw')->get('id')))?"state-error":""; ?>">
											<?php echo $this->formtext($this->form->get('atdw')->get('id')->setAttribute('class', 'input-sm'))?>
										</label>
										<div class="note">Area Id of ATDW for parent area</div>							
									</section>
								</fieldset>
								
								<header>
									<?php echo $this->translate('Expedia')?>
								</header>
								
								<fieldset>
									<section>
										<label class="label"><?php echo $this->translate('Enable')?></label>
										<label class="checkbox">
											<?php echo $this->formrow($this->form->get('expedia')->get('enable'))?>
											<i></i> </label>
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Expedia Area Id')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('expedia')->get('id')))?"state-error":""; ?>">
											<?php echo $this->formtext($this->form->get('expedia')->get('id')->setAttribute('class', 'input-sm'))?>
										</label>
										<div class="note">Area id of Expedia for parent area</div>							
									</section>
								</fieldset>
								
								<header>
									<?php echo $this->translate('V3')?>
								</header>
								
								<fieldset>
									<section>
										<label class="label"><?php echo $this->translate('Enable')?></label>
										<label class="checkbox">
											<?php echo $this->formrow($this->form->get('v3')->get('enable'))?>
											<i></i> </label>
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('V3 Area Id')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('v3')->get('id')))?"state-error":""; ?>">
											<?php echo $this->formtext($this->form->get('v3')->get('id')->setAttribute('class', 'input-sm'))?>
										</label>
										<div class="note">Area Id of V3 for parent area</div>							
									</section>
								</fieldset>
								
								<header>
									<?php echo $this->translate('Viator')?>
								</header>
								
								<fieldset>
									<section>
										<label class="label"><?php echo $this->translate('Enable')?></label>
										<label class="checkbox">
											<?php echo $this->formrow($this->form->get('viator')->get('enable'))?>
											<i></i> </label>
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Viator Area Id')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('viator')->get('id')))?"state-error":""; ?>">
											<?php echo $this->formtext($this->form->get('viator')->get('id')->setAttribute('class', 'input-sm'))?>
										</label>
										<div class="note">Area Id of Viator for parent area</div>							
									</section>
                                    
                                    <section>
                                        <label class="label"><?php echo $this->translate('Viator Keyword')?></label>
                                        <label class="input <?php echo ($this->formElementErrors($this->form->get('viator')->get('keyword')))?"state-error":""; ?>">
                                            <?php echo $this->formtext($this->form->get('viator')->get('keyword')->setAttribute('class', 'input-sm'))?>
                                        </label>
                                        <div class="note">Keyword for viator search</div>
                                    </section>
								</fieldset>
								
								<header>
									<?php echo $this->translate('Yelp')?>
								</header>
								
								<fieldset>
									<section>
										<label class="label"><?php echo $this->translate('Enable')?></label>
										<label class="checkbox">
											<?php echo $this->formrow($this->form->get('yelp')->get('enable'))?>
											<i></i> </label>
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Yelp Area Id')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('yelp')->get('id')))?"state-error":""; ?>">
											<?php echo $this->formtext($this->form->get('yelp')->get('id')->setAttribute('class', 'input-sm'))?>
										</label>
										<div class="note">Area Id of Yelp for parent area</div>							
									</section>
								</fieldset>
								
								<footer>
									<?php echo $this->formsubmit($this->form->get('save')->setAttribute('class', 'btn btn-primary'))?>															
									
								</footer>
							</div>
							<?php echo $this->form()->closeTag($this->form); ?>
						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
	
				</div>
				<!-- end widget -->
		
			</div>
			<!-- END COL -->
		
		</div>
		
		<!-- END ROW -->
	</section>
</div>