<!-- RIBBON -->
<div id="ribbon">

	<span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

	<!-- breadcrumb -->
	<ol class="breadcrumb">
		<li>Admin</li><li>Settings</li><li>Site</li>
	</ol>
	<!-- end breadcrumb -->

	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->

</div>
<!-- MAIN CONTENT -->
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark">
				<i class="fa fa-edit fa-fw "></i> 
					Settings 
				<span>> 
					Site
				</span>
			</h1>
		</div>
	</div>
	
	<!-- widget grid -->
	<section id="widget-grid" class="">
	
		<!-- START ROW -->
	
		<div class="row">
	
			<!-- NEW COL START -->
			<div class="col-sm-12 col-md-12 col-lg-6 ">
	
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false">
					<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
	
					data-widget-colorbutton="false"
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true"
					data-widget-sortable="false"
	
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
						<h2><?php echo $this->translate('Site settings')?></h2>
	
					</header>
	
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body no-padding">
							<?php $this->form->prepare(); ?>
							<?php echo $this->form()->openTag($this->form);?>
							<div class="smart-form">
								<fieldset>
									<section>
										<label class="label"><?php echo $this->translate('Site name')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('name')))?"state-error":""; ?>">
											<?php echo $this->formrow($this->form->get('name')->setAttribute('class', 'input-sm'))?>
										</label>										
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Url')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('url')))?"state-error":""; ?>">
											<?php echo $this->formrow($this->form->get('url')->setAttribute('class', 'input-sm'))?>
										</label>
										<div class="note">without "http://" eg. "example.com"</div>									
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Primary Email')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('email')))?"state-error":""; ?>">
											<?php echo $this->formrow($this->form->get('email')->setAttribute('class', 'input-sm'))?>
										</label>										
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Admin Email')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('adminemail')))?"state-error":""; ?>">
											<?php echo $this->formrow($this->form->get('adminemail')->setAttribute('class', 'input-sm'))?>
										</label>										
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Default front page')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('frontpage')))?"state-error":""; ?>">
											<?php echo $this->formrow($this->form->get('frontpage')->setAttribute('class', 'input-sm'))?>
										</label>
										<div class="note">eg. /content to show list of latest updates (blog style)</div>								
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Logo')?></label>
										<label for="file" class="input input-file">
											<div class="button">
												<?php echo $this->formElement($this->form->get('logo')->setAttribute('onchange', 'this.parentNode.nextSibling.value = this.value'))?>Browse
											</div><input type="text" placeholder="Include logo image" readonly="" class="input-sm">																							
										</label>									
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Support Email')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('supportemail')))?"state-error":""; ?>">
											<?php echo $this->formrow($this->form->get('supportemail')->setAttribute('class', 'input-sm'))?>
										</label>																		
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Site Category')?></label>
										<label class="select select-multiple">
											<?php echo $this->formrow($this->form->get('category')->setAttribute('class', 'custom-scroll')->setAttribute('multiple', 'multiple')->setAttribute('rows', '3'))?>
										</label>
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('One-type limit in drop down search')?></label>
										<label class="input <?php echo ($this->formElementErrors($this->form->get('dropdownlimit')))?"state-error":""; ?>">
											<?php echo $this->formrow($this->form->get('dropdownlimit')->setAttribute('class', 'input-sm'))?>
										</label>																		
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Zend Debug Status')?></label>
										<div class="inline-group">
											<?php $radios = $this->form->get('zfdebug')->getValueOptions(); ?>
											<?php foreach($radios as $key => $val): ?>
												<label class="radio">
													<input type="radio" name="zfdebug" value="<?php echo $key; ?>" <?php echo ($this->form->get('zfdebug')->getValue() == $key)?'checked="checked"':''; ?>>
													<i></i><?php echo $val; ?>
												</label>
											<?php endforeach; ?>
										</div>
									</section>
									<?php echo $this->formhidden($this->form->get('frm_type'))?>
									
								</fieldset>
								
								<footer>
									<?php echo $this->formsubmit($this->form->get('submit')->setAttribute('class', 'btn btn-primary'))?>															
									
								</footer>
							</div>
							<?php echo $this->form()->closeTag($this->form); ?>
						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
	
				</div>
				<!-- end widget -->
		
			</div>
			<!-- END COL -->
		
		</div>
		
		<!-- END ROW -->
	</section>
</div>