
<!-- widget grid -->
<section id="widget-grid" class="">

	<!-- START ROW -->

	<div class="row">

		<!-- NEW COL START -->
		<div class="col-sm-12 col-md-12 col-lg-12 ">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false">
				<!-- widget options:
				usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

				data-widget-colorbutton="false"
				data-widget-editbutton="false"
				data-widget-togglebutton="false"
				data-widget-deletebutton="false"
				data-widget-fullscreenbutton="false"
				data-widget-custombutton="false"
				data-widget-collapsed="true"
				data-widget-sortable="false"

				-->
				<header>
					<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
					<h2>General</h2>

				</header>

				<!-- widget div-->
				<div>

					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body no-padding">
						<?php $this->siteBlogSettingsForm->setAttribute('action', $this->action)?>
						<?php $this->siteBlogSettingsForm->prepare();?>
						<?php echo $this->form()->openTag($this->siteBlogSettingsForm)?>
						<div class="smart-form">
							<fieldset>
								<section>
									<label class="label"><?php echo $this->translate('Blog Feed Url')?></label>
									<label class="input <?php echo ($this->formElementErrors($this->siteBlogSettingsForm->get('blogfeed')))?"state-error":""; ?>">
										<?php echo $this->formrow($this->siteBlogSettingsForm->get('blogfeed')->setAttribute('class', 'input-sm'))?>
									</label>
									<div class="note">
										The Location that the blogs feed is located http://www.domain.com/blog/feed
									</div>
								</section>
							</fieldset>
							
							<fieldset>
								<?php echo $this->formrow($this->siteBlogSettingsForm->get('frm_type'))?>
								
								<section>
									<label class="label"><?php echo $this->translate('Blog Url')?></label>
									<label class="input <?php echo ($this->formElementErrors($this->siteBlogSettingsForm->get('blog_url')))?"state-error":""; ?>">
										<?php echo $this->formrow($this->siteBlogSettingsForm->get('blog_url')->setAttribute('class', 'input-sm'))?>
									</label>
									<div class="note">
										The Location that the blog is located at usually http://www.domain.com/blog, also might be a relative path eg. /blog
									</div>
								</section>
								
								<section>
									<label class="label"><?php echo $this->translate('Blog User')?></label>
									<label class="input <?php echo ($this->formElementErrors($this->siteBlogSettingsForm->get('blog_user')))?"state-error":""; ?>">
										<?php echo $this->formrow($this->siteBlogSettingsForm->get('blog_user')->setAttribute('class', 'input-sm'))?>
									</label>
									<div class="note">
										The Username to login to blog
									</div>
								</section>
								
								<section>
									<label class="label"><?php echo $this->translate('Blog Password')?></label>
									<label class="input <?php echo ($this->formElementErrors($this->siteBlogSettingsForm->get('blog_pass')))?"state-error":""; ?>">
										<?php echo $this->formrow($this->siteBlogSettingsForm->get('blog_pass')->setAttribute('class', 'input-sm'))?>
									</label>
									<div class="note">
										The pass to login to blog
									</div>
								</section>
							</fieldset>
							
							<footer>
								<?php echo $this->formsubmit($this->siteBlogSettingsForm->get('submit')->setAttribute('class', 'btn btn-primary'))?>															
								
							</footer>
						</div>
						<?php echo $this->form()->closeTag($this->siteBlogSettingsForm); ?>
					</div>
					<!-- end widget content -->

				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->
	
		</div>
		<!-- END COL -->
	
	</div>
	
	<!-- END ROW -->
</section>