<!-- RIBBON -->
<div id="ribbon">

	<span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

	<!-- breadcrumb -->
	<ol class="breadcrumb">
		<li>Admin</li><li>Settings</li><li>Status</li>
	</ol>
	<!-- end breadcrumb -->

	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->

</div>
<!-- MAIN CONTENT -->
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark">
				<i class="fa fa-edit fa-fw "></i> 
					Settings 
				<span>> 
					Status
				</span>
			</h1>
		</div>
	</div>
	
	<!-- widget grid -->
	<section id="widget-grid" class="">
	
		<?php if ($this->status == 'saved'): ?>
		    <div class="alert alert-success fade in">
				<button class="close" data-dismiss="alert">
					×
				</button>
				<i class="fa-fw fa fa-check"></i>
				Settings saved successfully.
			</div>
		<?php endif; ?>
		<!-- START ROW -->
	
		<div class="row">
	
			<!-- NEW COL START -->
			<div class="col-sm-12 col-md-12 col-lg-6 ">
	
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false">
					<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
	
					data-widget-colorbutton="false"
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true"
					data-widget-sortable="false"
	
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
						<h2><?php echo $this->translate('Site Status Settings')?></h2>
	
					</header>
	
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body no-padding">
							<?php $form = $this->form; ?>
							<?php $form->prepare(); ?>
							<?php $form->setAttribute('method', 'post'); ?>
							<?php echo $this->form()->openTag($form);?>
							<div class="smart-form">
								<fieldset>
									<section>
										<label class="label"><?php echo $this->translate('Site status')?></label>
										<div class="inline-group">
											<?php $radios = $form->get('maintenance')->getValueOptions(); ?>
											<?php foreach($radios as $key => $val): ?>
												<label class="radio">
													<input type="radio" name="zfdebug" value="<?php echo $key; ?>" <?php echo ($form->get('maintenance')->getValue() == $key)?'checked="checked"':''; ?>>
													<i></i><?php echo $val; ?>
												</label>
											<?php endforeach; ?>
										</div>
									</section>
									
									<section>
										<label class="label"><?php echo $this->translate('Maintenance Message')?></label>
										<label class="textarea">
											<?php echo $this->formrow($form->get('maintenance_msg')->setAttribute('class', 'custom-scroll input-sm')->setAttribute('rows', '3'))?>										
										</label>									
									</section>
									<?php echo $this->formhidden($form->get('frm_type'));?>
								</fieldset>
								
								<footer>
									<?php echo $this->formsubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'))?>															
									
								</footer>
							</div>
							<?php echo $this->form()->closeTag($form); ?>
						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
	
				</div>
				<!-- end widget -->
		
			</div>
			<!-- END COL -->
		
		</div>
		
		<!-- END ROW -->
	</section>
</div>