<div class="row-fluid">
    <? echo $this->form()->openTag($this->form);?>
    <div class="span12">
        <div class="widget wblue">
            <div class="widget-head">
                <div class="pull-left"><?php echo $this->translate('Destination')?></div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="row-fluid">
                    <div class="padd">
                        <p><strong>Are you sure you want to delete the following item<?=(sizeof($this->items)>1)?'s':''?>?</strong></p><br />
                        <ul class="itemsToDelete">
                            <?foreach ($this->items as $item):?>
                                <li><strong>Title:</strong> <?=$item->baodestination_name?>(<?=$item->baodestination_id?>)</li>
                            <?endforeach;?>
                        </ul>
                        <?php echo $this->formrow($this->form->get('confirm'))?>
                        <?php echo $this->formrow($this->form->get('multiact'))?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <?php echo $this->formsubmit($this->form->get('submitbtn'))?>
    </div>
    <br/>
    <br/>
    <? echo $this->form()->closeTag($this->form);?>
</div>