<?php if ($this->pageCount): ?>
    <div class="text-center">
		<ul class="pagination pagination-sm">
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a id="pager_first" href="<?php echo $this->url('zfcadmin/localdata/destination', array('page'=>$this->first,))?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a id="pager_previous" href="<?php echo $this->url('zfcadmin/localdata/destination', array('page'=>$this->previous,))?>"><i class="fa fa-angle-left"></i></a></li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a id="pager_<?php echo $page;?>" href="<?php echo $this->url('zfcadmin/localdata/destination', array('page'=>$page,))?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a id="pager_next" href="<?php echo $this->url('zfcadmin/localdata/destination', array('page'=>$this->next,))?>"><i class="fa fa-angle-right"></i></a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a id="pager_last" href="<?php echo $this->url('zfcadmin/localdata/destination', array('page'=>$this->last,))?>">&raquo;</a></li>
        </ul>
    </div>
<?php endif; ?>
