<!-- RIBBON -->
<div id="ribbon">

	<span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

	<!-- breadcrumb -->
	<ol class="breadcrumb">
		<li>Admin</li><li>Local Data</li><li>Information</li>
	</ol>
	<!-- end breadcrumb -->

	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->

</div>
<!-- MAIN CONTENT -->
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark">
				<i class="fa fa-edit fa-fw "></i> 
					Local Data 
				<span>> 
					Information
				</span>
			</h1>
		</div>
	</div>
		
	<!-- widget grid -->
	<section id="widget-grid" class="">
	
		<!-- START ROW -->
	
		<div class="row">
	
			<!-- NEW COL START -->
			<div class="col-sm-12 col-md-12 col-lg-6 ">
	
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false">
					<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
	
					data-widget-colorbutton="false"
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true"
					data-widget-sortable="false"
	
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
						<h2><?php echo $this->translate('Destination')?></h2>
	
					</header>
	
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body information-content">
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalDestinationCnt'] ?></span>
	                                <?php echo $this->translate('Total Destinations')?>
	                            </a>
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalDestinationStateCnt'] ?></span>
	                                <?php echo $this->translate('Total States')?>
	                            </a>
								
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalDestinationRegionCnt'] ?></span>
	                                <?php echo $this->translate('Total Regions')?>
	                            </a>
							</div>
						
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalDestinationAreaCnt'] ?></span>
	                                <?php echo $this->translate('Total Areas')?>
	                            </a>
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalDestinationCityCnt'] ?></span>
	                                <?php echo $this->translate('Total Cities')?>
	                            </a>
							</div>
						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
	
				</div>
				<!-- end widget -->
		
			</div>
			<!-- END COL -->
			
			<!-- NEW COL START -->
			<div class="col-sm-12 col-md-12 col-lg-6 ">
	
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
					<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
	
					data-widget-colorbutton="false"
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true"
					data-widget-sortable="false"
	
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
						<h2><?php echo $this->translate('PRODUCTS')?></h2>
	
					</header>
	
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body information-content">
							<div class="row">
								<a href="#">
	                                <a href="#">
		                                <span><?= $this->result['totalProductCnt'] ?></span>
		                                <?php echo $this->translate('Total Products')?>
		                            </a>
	                            </a>
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalAccomProductCnt'] ?></span>
	                                <?php echo $this->translate('Total Accommodation')?>
	                            </a>
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalAttrProductCnt'] ?></span>
	                                <?php echo $this->translate('Total Attractions')?>
	                            </a>
							</div>
						
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalEventProductCnt'] ?></span>
	                                <?php echo $this->translate('Total Events')?>
	                            </a>
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalTourProductCnt'] ?></span>
	                                <?php echo $this->translate('Total Tours')?>
	                            </a>
							</div>
						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
	
				</div>
				<!-- end widget -->
		
			</div>
			<!-- END COL -->
		
		</div>
		
		<!-- END ROW -->
		
		<!-- START ROW -->
	
		<div class="row">
	
			<!-- NEW COL START -->
			<div class="col-sm-12 col-md-12 col-lg-6 ">
	
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget jarviswidget-color-darken" id="wid-id-2" data-widget-editbutton="false" data-widget-custombutton="false">
					<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
	
					data-widget-colorbutton="false"
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true"
					data-widget-sortable="false"
	
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
						<h2><?php echo $this->translate('PROVIDERS')?></h2>
	
					</header>
	
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body information-content">
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalAtdwProductCnt'] ?></span>
	                                <?php echo $this->translate('ATDW')?>
	                            </a>
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalRoamProductCnt'] ?></span>
	                                <?php echo $this->translate('Roamfree')?>
	                            </a>								
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalV3ProductCnt'] ?></span>
	                                <?php echo $this->translate('V3')?>
	                            </a>
							</div>
						
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalHcProductCnt'] ?></span>
	                                <?php echo $this->translate('Hotels Combined')?>
	                            </a>
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalViatorProductCnt'] ?></span>
	                                <?php echo $this->translate('Viator')?>
	                            </a>
							</div>
							
							<div class="row">
								<a href="#">
	                                <span><?= $this->result['totalExpdProductCnt'] ?></span>
	                                <?php echo $this->translate('Expedia')?>
	                            </a>
							</div>
						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
	
				</div>
				<!-- end widget -->
		
			</div>
			<!-- END COL -->
			
			<!-- NEW COL START -->
			<div class="col-sm-12 col-md-12 col-lg-6 ">
	
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget jarviswidget-color-darken" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false">
					<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
	
					data-widget-colorbutton="false"
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true"
					data-widget-sortable="false"
	
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
						<h2><?php echo $this->translate('UPDATES')?></h2>
	
					</header>
	
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body information-content">
							<div class="row">
								
                                <a href="#">
	                                <span></span>
	                                <?php echo $this->translate('Last Update')?>
	                            </a>	                        
							</div>
						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
	
				</div>
				<!-- end widget -->
		
			</div>
			<!-- END COL -->
		
		</div>
		
		<!-- END ROW -->
	</section>
</div>