<div class="container">
<br>
<div class="row">
<div class="span9">
    <div class="well">
        <div class="container">
            <div class="row">
                <div class="span8">
                    <div class="page-header">
                        <h1><?php echo $this->product->title; ?>
                            <small>- <?php echo $this->destination->destinationName; ?></small>
                        </h1>
                    </div>
                </div>
            </div> 

            <div class="container">
                <div class="row">
                    <div class="span8">
                    	<div>
                    		<h2><?php echo $this->tourTitle;?> - <?php echo $this->tourPrice;?></h2>
                    		<p><?php echo $this->tourDescription;?></p>
                    	</div>
                        <div class="well">
                            <h4 class="calendar_month">
                                <?php echo date("F Y", mktime(0,0,0, $this->selectedMonth, 1, $this->selectedYear)); ?>
                            </h4>
                            <p class="selectMonth">
                            	<span>Select Month</span>
                            	<select name="anotherMonth" id="anotherMonth">
                            		<?php
                            		for ($i = 0; $i < 12; $i++){
                            			$selected = "";
                            			if (date("Y-m", mktime(0,0,0, $this->selectedMonth, 1, $this->selectedYear)) == date("Y-m", mktime(0,0,0,date("m") + $i, 1, date("Y"))))
											$selected = " selected";
                            			echo "<option value='".date("Y-m-d", mktime(0,0,0,date("m") + $i, 1, date("Y")))."'".$selected.">".date("Y-m", mktime(0,0,0,date("m") + $i, 1, date("Y")))."</option>";
                            		}?>
                            	</select>
                            </p>
                            <div class="calendardate span7" id="calendarBlock">
                            	<table class="">
                            		<thead>
	                            		<tr class="calendardatehead">
	                            			<td>Sunday</td>
	                            			<td>Monday</td>
	                            			<td>Tuesday</td>
	                            			<td>Wednesday</td>
	                            			<td>Thursday</td>
	                            			<td>Friday</td>
	                            			<td>Saturday</td>
	                            		</tr>
                            		</thead>
                            		<tbody>
                            			<?php 
											$timestamp = mktime(0,0,0,$this->selectedMonth,1,$this->selectedYear);
											$maxday = date("t",$timestamp);
											$thismonth = getdate ($timestamp);
											$startday = $thismonth['wday'];
											for ($i=0; $i<($maxday+$startday); $i++) {
												if(($i % 7) == 0 ) echo '<tr class="daterow">';
												if ($i < $startday) echo '<td class="blank span1"><a ></a></td>';
												else{
													$curDay = $i - $startday + 1;
													$curDate = date("Y-m-d", mktime(0,0,0, $this->selectedMonth, $curDay, $this->selectedYear));
													if (!$this->tours[$curDate]){
														echo '<td class="na span1"><a><em>'.$curDay.'</em><strong>NOT AVAILABLE</strong></a></td>';
													}else{
														echo '<td class="av span1"><a><em>'.$curDay.'</em><strong><em class="price">'.$this->tours[$curDate]->retailPriceFormatted.'</em></a></td>';
													}
												}
												if(($i % 7) == 6 ) echo "</tr>";
											}
											if (($maxday + $startday) % 7 != 0){
												for ($i =0; $i < 7-(($maxday + $startday) % 7); $i++){
													echo "<td class='blank span1'><a></a></td>";
												}
												echo "</tr>";
											}
										?>
                            		</tbody>
                            	</table>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div class="well">
                            <h3>
                                <?php echo $this->translate('Tour grades'); ?>
                            </h3>

                            <table class="table">
                                <?php foreach ($this->product->tourGrades as $tour) {?>
                                <tr>
                                    <td><a href="<?php echo $this->url("tours", array("action"=>"tourcalendar", "id"=>$this->product->code), array("query"=> array("tourid"=>$tour->gradeCode, "listdate"=>date("Y-m-d"))));?>"><strong><?php echo $tour->gradeTitle;?></strong></a></td>
                                    <td><?php echo $tour->gradeDescription; ?></td>
                                    <td><?php echo $tour->priceFromFormatted; ?></td>
                                </tr>
                                <?php }?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


<div class="span3">

    <div class="nav nav-tabs nav-stacked" style="background:white; font-size:11px; ">
        <ul>
        <li class="active" style="font-size:12px; font-weight:bold;"><a href="#"><?php echo $this->translate('Explore'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-envelope"></i><?php echo $this->translate('Email this Listing'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-envelope"></i><?php echo $this->translate('Add to Travel Planner'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-print"></i><?php echo $this->translate('Print Listing'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-star"></i><?php echo $this->translate('Add to Favourites'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-search"></i><?php echo $this->translate('View Similar Properties'); ?></a></li>
        </ul>
    </div>

    <ul class="nav nav-tabs nav-stacked">
        <li>
            <div id="propertyMap"></div>
        </li>

    </ul>
</div>
</div>

<script type="text/javascript">
    google.maps.visualRefresh = true;
    var propertyLocation = new google.maps.LatLng(<?php echo $this->destination->latitude?>, <?php echo $this->destination->longitude?>);
    var map;
    var marker;
    function initialize() {
        var mapOptions = {
            zoom: 17,
            center: propertyLocation,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById('propertyMap'), mapOptions);

        marker = new google.maps.Marker({
            map: map,
            title: '<?php echo $this->product->title; ?>',
            position: propertyLocation
        });
    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<!-- End Slider/Search Block -->
<script>
    $(document).ready(function(){
            $( "#anotherMonth" ).change(function(){
            	document.location.href = "<?php echo $this->url("tours", array("action"=>"tourcalendar", "id"=>$this->product->code), array("query"=> array("tourid"=>$this->tourId)))?>" + "&listdate="+$(this).val();
            });
        });
    
</script>
</div> <!-- /container -->