<div class="container">
<br>
<div class="row">
<div class="span9">
    <div class="well">
        <div class="container">
            <div class="row">
                <div class="span8">
                    <div class="page-header">
                        <h1><?php echo $this->product->title; ?>
                            <small>- <?php echo $this->destination->destinationName; ?></small>
                            <p style="font-size:23px; padding:10px; float:right;" class="label label-success"><?php echo $this->product->priceFormatted;?></p>
                        </h1>
                    </div>


                    <?php /********************* standard slideshow for low res images ****************************/ ?>

                    <?php if ($this->productPhotos): ?> 
                        <!-- Photo Gallery -->
                        <div id="gallery" class="carousel slide">
                            <div class="carousel-content">
                                <?php foreach ($this->productPhotos as $i => $image): ?>
                                    <div class="<?php $i != 0 || print 'active ' ?>item">
                                        <img src="<?php echo $image->photoURL ?>" border="0"/>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <a style="line-height: 27px;" class="carousel-control left" href="#gallery"
                               data-slide="prev">&lsaquo;</a>
                            <a style="line-height: 27px;" class="carousel-control right" href="#gallery"
                               data-slide="next">&rsaquo;</a>

                            <div class="my-carousel-indicators">
                                <?php foreach ($this->productPhotos as $i => $image): ?>
                                    <div class="gallery-thumb-wrapper">
                                        <div class="gallery-thumb"><img data-target="#gallery"
                                                                        data-slide-to="<?php echo $i ?>"
                                                                        src="<?php echo $image->thumbnailURL ?>"
                                                                        border="0"/></div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <script type="text/javascript">
                        $(document).ready(function () {
                            var maxHeight = 0;
                            var minHeight = 999999;
                            var images = []
                            $('.item > img').each(function (i) {
                                var src = $(this).attr('src');
                                images[i] = new Image();

                                images[i].onload = function () {
                                    var height = images[i].height;
                                    /*if (height > maxHeight) {
                                        maxHeight = height;
                                        $('.carousel-content').height(maxHeight);
                                    }*/
                                    if (height < minHeight) {
                                        minHeight = height;
                                        $('.carousel-content').height(minHeight);
                                    }
                                }
                                images[i].src = src;
                            });
                        });
                    </script>

                    <!--/ Photo Gallery -->

                </div>

            </div>

            <div class="container">
                <div class="row">
                    <div class="span8">
                        <div class="well">
                            <h3>
                                <?php echo $this->translate('Property Information'); ?>
                            </h3>

                            <dl class="dl-horizontal">
                                <dt><?php echo $this->translate('Description') ?></dt>
                                <dd><?php echo $this->product->description ?></dd>
                                <dt><?php echo $this->translate('Departure') ?></dt>
                                <dd><?php echo $this->product->departurePoint?></dd>
                                <dt><?php echo $this->translate('Inclusions') ?></dt>
                                <?php foreach($this->product->inclusions as $incl){?>
                                    <dd><?php echo $incl?></dd>
                                <?php }?>
                            </dl>
                        </div>
                        <div class="well">
                            <h3>
                                <?php echo $this->translate('Tour grades'); ?>
                            </h3>

                            <table class="table">
                                <?php foreach ($this->product->tourGrades as $tour) {?>
                                <tr>
                                    <td><a href="<?php echo $this->url("tours", array("action"=>"tourcalendar", "id"=>$this->product->code), array("query"=> array("tourid"=>$tour->gradeCode, "listdate"=>date("Y-m-d"))));?>"><strong><?php echo $tour->gradeTitle;?></strong></a></td>
                                    <td><?php echo $tour->gradeDescription; ?></td>
                                    <td><?php echo $tour->priceFromFormatted; ?></td>
                                </tr>
                                <?php }?>
                            </table>
                        </div>
                    </div>
                </div>
                
                <?php //var_dump($this->product);?>
                <!--
                <?php if ($product_info->attributes): ?>
                    <div class="row">
                        <div class="span8">
                            <div class="well">
                                <h3><?php echo $this->translate('Facilities') ?></h3>
                                <?php foreach ($product_info->attributes as $attr): ?>
                                    <?php if ($attr['attr_type'] == 'Entity Facility') : ?>
                                        <span class="label label-info "
                                              style="line-height:28px; "><?php echo $attr['attr_name'] ?></span>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if ($product_info->hotel_rooms): ?>
                    <div class="row">
                        <div class="span8">
                            <h3><?php echo $this->translate('Room Descriptions') ?></h3>
                            <?php foreach ($product_info->hotel_rooms as $room): ?>
                                <div class="well"><h4><?php echo $room['room_name'] ?></h4>

                                    <p><?php echo $room['room_description'] ?></p>
                                    <?php if ($product_info->product_checkout): ?>
                                        <dt><?php echo $this->translate('Check Out') ?></dt>
                                        <dd><?php echo $product_info->product_checkout; ?></dd>
                                    <?php endif; ?>

                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($product_info->product_info): ?>
                    <div class="row">
                        <div class="span8">
                            <div class="well">
                                <h3><?php echo $this->translate('Property Policies') ?></h3>
                                <dl class="dl-horizontal">
                                    <?php foreach ($product_info->product_info as $info): ?>
                                        <?php if ($info['info_title'] != 'V3 State ID' && $info['info_title'] != 'V3 Region ID'): ?>
                                            <dt><?php echo $info['info_title'] ?></dt>
                                            <dd><?php echo $info['info_body'] ?></dd>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </dl>
                            </div>
                        </div>
                    </div> 
                <?php endif; ?>
                -->
            </div>

        </div>
    </div>
</div>


<div class="span3">

    <div class="nav nav-tabs nav-stacked" style="background:white; font-size:11px; ">
        <ul>
        <li class="active" style="font-size:12px; font-weight:bold;"><a href="#"><?php echo $this->translate('Explore'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-envelope"></i><?php echo $this->translate('Email this Listing'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-envelope"></i><?php echo $this->translate('Add to Travel Planner'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-print"></i><?php echo $this->translate('Print Listing'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-star"></i><?php echo $this->translate('Add to Favourites'); ?></a></li>
        <li><a href="#"><i style="padding-right:10px; margin-top:2px"
                           class="icon-search"></i><?php echo $this->translate('View Similar Properties'); ?></a></li>
        </ul>
    </div>

    <?php echo $this->form()->openTag($this->toursForm);?>
    <ul class="nav nav-tabs nav-stacked" style="background:white; font-size:11px; ">
        <li class="active" style="font-size:12px; font-weight:bold;">
            <a href="#"><?php echo $this->translate('Check Availability') ?></a>
            <div class="control-group">
                <label for="commenceMonth"><?php echo $this->translate('Date')?></label>
                <div class="controls">
                    <?php echo $this->formrow($this->toursForm->get('commenceMonth')->setAttribute('style', 'width:100px'))?>
                    <?php echo $this->formrow($this->toursForm->get('commenceDate')->setAttribute('class', 'span1'))?>
                </div>
            </div>
            <?php foreach($this->product->ageBands as $key=>$band){?>
                <label for="ageSelect"><?php echo $this->translate($band->description)."(".$this->translate("Age")." : ".$band->ageFrom." to ".$band->ageTo.")"?></label>
                <?php echo $this->formselect($this->toursForm->get('ageBand['.$band->bandId.']')->setAttribute('class', 'span2'))?>
            <?php }?>
            <div class="form-action">
                <?php echo $this->formsubmit($this->toursForm->get('submit-bookingForm'))?>
            </div>
        </li>
    </ul>
    <?php echo $this->form()->closeTag($this->toursForm);?>

    <ul class="nav nav-tabs nav-stacked">
        <li>
            <div id="propertyMap"></div>
        </li>

    </ul>
</div>
</div>

<script type="text/javascript">
    google.maps.visualRefresh = true;
    var propertyLocation = new google.maps.LatLng(<?php echo $this->destination->latitude?>, <?php echo $this->destination->longitude?>);
    var map;
    var marker;
    function initialize() {
        var mapOptions = {
            zoom: 17,
            center: propertyLocation,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById('propertyMap'), mapOptions);

        marker = new google.maps.Marker({
            map: map,
            title: '<?php echo $this->product->title; ?>',
            position: propertyLocation
        });
    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<!-- End Slider/Search Block -->
<script>
    $(document).ready(function(){
        var productId = '<?php echo $this->product->code;?>';
        $( "#commenceMonth" ).change(function(){
            $.ajax({
                url:'<?php echo $this->url('tours', array("action"=>"getDates"));?>',
                data : {productId : productId, month : $(this).val()},
                method : "post",
                success : function(data){
                    console.log(data);
                    $("#commenceDate").html(data);
                }
            });
        });
    });
</script>
</div> <!-- /container -->