<!-- NEW COL START -->
<article class="col-sm-12 col-md-12 col-lg-6">

	<!-- Widget ID (each widget will need unique ID)-->
	<div class="jarviswidget" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
		<!-- widget options:
		usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

		data-widget-colorbutton="false"
		data-widget-editbutton="false"
		data-widget-togglebutton="false"
		data-widget-deletebutton="false"
		data-widget-fullscreenbutton="false"
		data-widget-custombutton="false"
		data-widget-collapsed="true"
		data-widget-sortable="false"

		-->
		<header>
			<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
			<h2><?php echo $this->title ?> </h2>

		</header>

		<!-- widget div-->
		<div>
			
			<!-- widget edit box -->
			<div class="jarviswidget-editbox">
				<!-- This area used as dropdown edit box -->

			</div>
			<!-- end widget edit box -->

			<!-- widget content -->
			<div class="widget-body no-padding">
				<?php $this->aliasForm->setAttribute('action', $this->action); ?>
				<?php $this->aliasForm->prepare(); ?>
				<?php echo $this->form()->openTag($this->aliasForm) ?>
				<div class="smart-form">
					
					<fieldset>
						<section>
							<label class="label"><?php echo $this->translate('Existing system path')?></label>
							<label class="input <?php echo ($this->formElementErrors($this->aliasForm->get('alias_system')))?"state-error":""; ?>">
								<?php echo $this->formRow($this->aliasForm->get('alias_system')->setAttribute('class', 'input-sm')) ?>
							</label>
							<div class="note">
								eg. /content/3
							</div>
						</section>
						
						<section>
							<label class="label"><?php echo $this->translate('Route')?></label>
							<label class="input <?php echo ($this->formElementErrors($this->aliasForm->get('alias_system')))?"state-error":""; ?>">
								<?php echo $this->formRow($this->aliasForm->get('alias_route')->setAttribute('class', 'input-sm')) ?>								 
							</label>
							<div class="note">
								eg. /services; /services/web-design
							</div>
						</section>
					</fieldset>
					<footer>
						<?php echo $this->formButton()->render($this->aliasForm->get('submit-aliasForm'), 'Save'); ?>																
						
					</footer>
				</div>
				<?php echo $this->form()->closeTag($this->aliasForm) ?>
			</div>
			<!-- end widget content -->

		</div>
		<!-- end widget div -->

	</div>
	<!-- end widget -->

</article>
<!-- END COL -->
