<!-- RIBBON -->
<div id="ribbon">

	<span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

	<!-- breadcrumb -->
	<ol class="breadcrumb">
		<li>Admin</li><li>Content</li><li>URL Aliases</li>
	</ol>
	<!-- end breadcrumb -->

	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->

</div>
<!-- MAIN CONTENT -->
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark">
				<i class="fa fa--building fa-fw "></i> 
					Content 
				<span>> 
					URL Aliases
				</span>
			</h1>
		</div>	
	</div>
	
	<!-- widget grid -->
	<section id="widget-grid" class="">
	
		<!-- row -->
		<div class="row">
	
			<!-- NEW WIDGET START -->
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
	
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
					<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
	
					data-widget-colorbutton="false"
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true"
					data-widget-sortable="false"
	
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-table"></i> </span>
						<h2>Aliases </h2>						
					</header>
	
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
						
						<div>
							

							<?php $this->aliasActionsForm->setAttribute('action', $this->url('zfcadmin/content/alias'))->setAttribute('class', "smart-form navbar-form"); ?>
							<?php $this->aliasActionsForm->prepare(); ?>
							<?php echo $this->form()->openTag($this->aliasActionsForm)?>
							
							<div class="widget-body">
								<table class="table smart-form table-bordered has-tickbox">
									<thead>
				                        <tr>
				                            <th><label class="checkbox">
												<input type="checkbox" class="checkall">
												<i></i> </label></th>
				                            <th><?php echo $this->translate('System path')?></th>
				                            <th><?php echo $this->translate('Alias')?></th>
				                            <th><?php echo $this->translate('Actions')?></th>
				                        </tr>
				                    </thead>
				                    <tbody>
				                        <?php foreach($this->aliasList as $alias): ?>
				                            <tr>
				                            	<td><label class="checkbox">
				                                	<input value="<?php echo $alias->getAliasId()?>" name="pages[]" type="checkbox">
				                                	<i></i> </label></td>
				                                <td><?php echo $alias->getAliasSystem()?></td>
				                                <td><?php echo $alias->getAliasRoute()?> <a target="_blank" href="<?php echo $alias->getAliasRoute() ?>"><i class="icon-share-alt"></i></a></td>
				                                <td>
				                                    <a href="<?php echo $this->url('zfcadmin/content/alias', array('action' => 'edit', 'id' => $alias->getAliasId()))?>" class="btn btn-mini"><i class="fa fa-edit"></i></a>
				                                    <a href="#deleteModal-<?php echo $alias->getAliasId()?>" class="delete-btn btn btn-mini"><i class="fa fa-times"></i></a>
				                                </td>
				                            </tr>
				                            <?php echo $this->partial('shared/modal/link-confirmation', array(
				                                'id'            => 'deleteModal-' . $alias->getAliasId(),
				                                'title'         => $this->translate('Action confirmation'),
				                                'body'          => $this->translate('You are about to delete an alias, continue?'),
				                                'confirmLabel'  => $this->translate('Delete alias'),
				                                'url'           => $this->url('zfcadmin/content/alias', array('action' => 'delete', 'id' => $alias->getAliasId())),
				                            )) ?>
				                        <?php endforeach;?>
				                    </tbody>
				                </table>	
								<div class="row action-div">
									<div class="form-group">
										<label class="select">
											<?php echo $this->formselect($this->aliasActionsForm->get('action'))?><i></i>
										</label>
									</div>
									<input type="button" id="bulkDelete" data-toggle="modal" role="button" class="btn btn-default" value="<?php echo $this->translate('Submit')?>" />	
								</div>
												
							</div>
							<!-- end widget content -->
							
							<?php echo $this->form()->closeTag($this->aliasActionsForm)?>
						</div>
		
					</div>
					<!-- end widget div -->
	
				</div>
				<!-- end widget -->
	
	
			</article>
			<!-- WIDGET END -->
			<?php echo $this->partial('admin/alias/alias-form', array(
	            'aliasForm' => $this->aliasForm,
	            'title' => $this->translate('Add alias'),
	            'action' => $this->url('zfcadmin/content/alias'))
	        )?>
	
		</div>
	
		<!-- end row -->
	
	</section>
	
	<div class="bulkDelete-modal" title=""  style="display:none;">
		<p><?php echo $this->translate('Performing action on one or more aliases, continue?')?></p>
	</div>
	
	<!-- end widget grid -->
	
	<script type="text/javascript">
	 	$('.checkall').on('click', function () {
	        $(this).closest('table').find(':checkbox').prop('checked', this.checked);
	    });
	    
		$('a.delete-btn').click(function() {
			$($(this).attr("href")).dialog('open');
			return false;
		});
		
		$('.confirm-modal').dialog({
			autoOpen : false,
			width : 400,
			resizable : false,
			modal : true,
			title : "Confirm Delete?",
			buttons : [{
				html : "<i class='fa fa-trash-o'></i>&nbsp; Delete aliase",
				"class" : "btn btn-danger",
				click : function() {
					window.location.href=$(this).attr("attr");				
				}
			}, {
				html : "<i class='fa fa-times'></i>&nbsp; Cancel",
				"class" : "btn btn-default",
				click : function() {
					$(this).dialog("close");
				}
			}]
		});
		
		$('#bulkDelete').click(function() {
			$('.bulkDelete-modal').dialog('open');
			return false;
		});
		
		$('.bulkDelete-modal').dialog({
			autoOpen : false,
			width : 400,
			resizable : false,
			modal : true,
			title : "<?php echo $this->translate('Action confirmation')?>",
			buttons : [{
				html : "<i class='fa fa-warning'></i>&nbsp; <?php echo $this->translate('Continue')?>",
				"class" : "btn btn-danger",
				click : function() {
					$('#aliasActionsForm').submit();				
				}
			}, {
				html : "<i class='fa fa-times'></i>&nbsp; Cancel",
				"class" : "btn btn-default",
				click : function() {
					$(this).dialog("close");
				}
			}]
		});
	
		// PAGE RELATED SCRIPTS
	
	</script>
</div>
