
<!-- widget grid -->
<section id="widget-grid" class="">

<?php $this->pageForm->setAttribute('action', $this->action)?>
<?php $this->pageForm->prepare();?>
<?php echo $this->form()->openTag($this->pageForm)?>

	<!-- START ROW -->

	<div class="row">

		<!-- NEW COL START -->
		<div class="col-sm-12 col-md-12 col-lg-12 ">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false">
				<!-- widget options:
				usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

				data-widget-colorbutton="false"
				data-widget-editbutton="false"
				data-widget-togglebutton="false"
				data-widget-deletebutton="false"
				data-widget-fullscreenbutton="false"
				data-widget-custombutton="false"
				data-widget-collapsed="true"
				data-widget-sortable="false"

				-->
				<header>
					<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
					<h2>General</h2>

				</header>

				<!-- widget div-->
				<div>

					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body no-padding">
						<div class="smart-form">
							<fieldset>
								<section>
									<label class="label"><?php echo $this->translate('Page title')?></label>
									<label class="input <?php echo ($this->formElementErrors($this->pageForm->get('content_title')))?"state-error":""; ?>">
										<?php echo $this->formrow($this->pageForm->get('content_title')->setAttribute('class', 'input-sm'))?>
									</label>
								</section>
								
								<section>
									<label class="label"><?php echo $this->translate('Content')?></label>
									<label class="input">
										<?php echo $this->formBootstrapEditor($this->pageForm->get('content_body'));?>
									</label>
								</section>
							</fieldset>
						</div>
					</div>
					<!-- end widget content -->

				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->
	
		</div>
		<!-- END COL -->
	
	</div>
	
	<!-- END ROW -->
		
	<!-- START ROW -->

	<div class="row">
		<!-- NEW COL START -->
		<article class="col-sm-12 col-md-12 col-lg-6">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
				<!-- widget options:
				usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

				data-widget-colorbutton="false"
				data-widget-editbutton="false"
				data-widget-togglebutton="false"
				data-widget-deletebutton="false"
				data-widget-fullscreenbutton="false"
				data-widget-custombutton="false"
				data-widget-collapsed="true"
				data-widget-sortable="false"

				-->
				<header>
					<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
					<h2><?php echo $this->translate('Menu item')?> </h2>

				</header>

				<!-- widget div-->
				<div>

					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body no-padding">

						<div class="smart-form">
							
							<fieldset>
								<section>
									<label class="label"><?php echo $this->translate('Menu item')?></label>
									<label class="input">
										<?php echo $this->formrow($this->pageForm->get('menu_input')->setAttribute('class', 'input-sm'))?>
									</label>
									<div class="note">
										leave blank if you don't want create a menu item
									</div>
								</section>
								
								<section>
									<label class="label"><?php echo $this->translate('Menu')?></label>
									<label class="select">
										<?php echo $this->formselect($this->pageForm->get('menu_select')->setAttribute('class', 'input-sm'))?>
										 <i></i> 
									</label>									
								</section>
								
								<section>
									<label class="label"><?php echo $this->translate('Menu item wieght')?></label>
									<label class="input <?php echo ($this->formElementErrors($this->pageForm->get('menu_weight')))?"state-error":""; ?>">
										<?php echo $this->formrow($this->pageForm->get('menu_weight')->setAttribute('class', 'input-sm'))?>
									</label>									
								</section>
							</fieldset>
						</div>
					</div>
					<!-- end widget content -->

				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->
	
		</article>
		<!-- END COL -->
		
		<!-- NEW COL START -->
		<article class="col-sm-12 col-md-12 col-lg-6">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget" id="wid-id-2" data-widget-editbutton="false" data-widget-custombutton="false">
				<!-- widget options:
				usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

				data-widget-colorbutton="false"
				data-widget-editbutton="false"
				data-widget-togglebutton="false"
				data-widget-deletebutton="false"
				data-widget-fullscreenbutton="false"
				data-widget-custombutton="false"
				data-widget-collapsed="true"
				data-widget-sortable="false"

				-->
				<header>
					<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
					<h2><?php echo $this->translate('Settings')?> </h2>

				</header>

				<!-- widget div-->
				<div>

					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body no-padding">

						<div class="smart-form">
							
							<fieldset>
								<section>
									<label class="label"><?php echo $this->translate('Url alias')?></label>
									<label class="input <?php echo ($this->formElementErrors($this->pageForm->get('alias_route')))?"state-error":""; ?>">
										<?php echo $this->formrow($this->pageForm->get('alias_route')->setAttribute('class', 'input-sm'))?>
									</label>
									<div class="note">
										<?php echo $this->translate('leave blank if you don\'t want to create an alias')?>
									</div>
								</section>
								
								<section>
									<label class="label"><?php echo $this->translate('Status')?></label>
									<label class="select">
										<?php echo $this->formselect($this->pageForm->get('content_status')->setAttribute('class', 'input-sm'))?>
										 <i></i> 
									</label>									
								</section>
																
							</fieldset>
						</div>
					</div>
					<!-- end widget content -->

				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->
	
		</article>
		<!-- END COL -->
								
	</div>
	
	<!-- END ROW -->
	
	<!-- START ROW -->

	<div class="row">

		<!-- NEW COL START -->
		<article class="col-sm-12 col-md-12 col-lg-12 ">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false">
				<!-- widget options:
				usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

				data-widget-colorbutton="false"
				data-widget-editbutton="false"
				data-widget-togglebutton="false"
				data-widget-deletebutton="false"
				data-widget-fullscreenbutton="false"
				data-widget-custombutton="false"
				data-widget-collapsed="true"
				data-widget-sortable="false"

				-->
				<header>
					<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
					<h2><?php echo $this->translate('SEO')?></h2>

				</header>

				<!-- widget div-->
				<div>

					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body no-padding">
						<div class="smart-form">
							<fieldset>
								<section>
									<label class="label"><?php echo $this->translate('Meta title')?></label>
									<label class="input">
										<?php echo $this->formrow($this->pageForm->get('content_metatitle')->setAttribute('class', 'input-sm'))?>										
									</label>
								</section>
								
								<section>
									<label class="label"><?php echo $this->translate('Meta keywords')?></label>
									<label class="textarea">
										<?php echo $this->formtextarea($this->pageForm->get('content_metakeywords')->setAttribute('class', 'custom-scroll input-sm')->setAttribute('rows', '3'))?>																				
									</label>
								</section>
								
								<section>
									<label class="label"><?php echo $this->translate('Meta description')?></label>
									<label class="textarea">
										<?php echo $this->formtextarea($this->pageForm->get('content_metadescription')->setAttribute('class', 'custom-scroll input-sm')->setAttribute('rows', '3'))?>																				
									</label>
								</section>
							</fieldset>
						</div>
					</div>
					<!-- end widget content -->

				</div>
				<!-- end widget div -->

			</article>
			<!-- end widget -->
	
		</div>
		<!-- END COL -->
	
	</div>
	
	<!-- END ROW -->
	
	<!-- START ROW -->

	<div class="row">

		<!-- NEW COL START -->
		<div class="col-sm-12 col-md-12 col-lg-12 ">
			<div class="smart-form">
				<footer>
					<?php echo $this->formButton()->render($this->pageForm->get('submit-pageForm'), 'Save page'); ?>															
					
				</footer>
			</div>
	
		</div>
		<!-- END COL -->
	
	</div>
	
	<!-- END ROW -->
	
                        
<?php echo $this->form()->closeTag($this->pageForm); ?>
</section>
